version: '3.8'

services:
  keycloak-db:
    image: postgres:13
    container_name: keycloak-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-keycloak}
      POSTGRES_USER: ${POSTGRES_USER:-keycloak}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    networks:
      - keycloak-network

  keycloak:
    build: .
    container_name: keycloak
    environment:
      DB_VENDOR: ${DB_VENDOR:-postgres}
      DB_ADDR: ${DB_ADDR:-keycloak-db}
      DB_DATABASE: ${DB_DATABASE:-keycloak}
      DB_USER: ${DB_USER:-keycloak}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
      KEYCLOAK_THEME: ${KEYCLOAK_THEME:-default}
      CLIENT_SECRET: ${CLIENT_SECRET:-default-client-secret}  # Keycloak client secret
      USER_PASSWORD: ${USER_PASSWORD:-default-user-password}  # User password
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID:-default-google-client-id}  # Google client ID
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET:-default-google-client-secret}  # Google client secret
      FACEBOOK_CLIENT_ID: ${FACEBOOK_CLIENT_ID:-default-facebook-client-id}
      FACEBOOK_CLIENT_SECRET: ${FACEBOOK_CLIENT_SECRET:-default-facebook-client-secret}
    ports:
      - "8080:8080"
    networks:
      - keycloak-network
    depends_on:
      - keycloak-db

volumes:
  keycloak-db-data:

networks:
  keycloak-network: